language: c

addons:
  apt:
    packages:
      - libenchant-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX="$HOME" ..
  - make
  - make test
  - make install
  - make test-install

compiler:
  - clang
  - gcc
