language: c

addons:
  apt:
    packages:
      - libenchant-dev

before_install:
  - test "$TRAVIS_OS_NAME" != 'osx' || brew install enchant

script: .ci

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
