#! /bin/sh
set -eu

semordnilap="${semordnilap:-semordnilap}"
word="$1"
drow="$2"
expected_stdout="$word -> $drow"
expected_exit_code="$3"

actual_exit_code=0
actual_stdout="$($semordnilap $word)" ||
actual_exit_code="$?"
test "$expected_stdout" = "$actual_stdout"
test "$expected_exit_code" -eq "$actual_exit_code"
