version: 2
jobs:
  arch:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run: |
          pacman --noconfirm --refresh --sync cmake clang enchant make
          mkdir build
          cd build
          cmake ..
          make
          make test
          make check
          make install
          make installcheck
          make pathcheck
  debian:
    docker:
      - image: debian
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y build-essential cmake libenchant-dev man
          mkdir build
          cd build
          cmake ..
          make
          make test
          make check
          make install
          make installcheck
          make pathcheck
  fedora:
    docker:
      - image: fedora
    steps:
      - checkout
      - run: |
          dnf -y install cmake enchant-devel findutils gcc man
          mkdir build
          cd build
          cmake ..
          make
          make test
          make check
          make install
          make installcheck
          make pathcheck
  macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: |
          brew install cmake enchant
          mkdir build
          cd build
          cmake ..
          make
          make test
          make check
          make install
          make installcheck
          make pathcheck
workflows:
  version: 2
  workflow:
    jobs:
      # arch
      - debian
      - fedora
      - macos
