version: 2
jobs:
  debian:
    docker:
      - image: debian
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y build-essential cmake libenchant-dev
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="$HOME" ..
          make
          make test
          make check
          make install
          make installcheck
  macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: |
          brew install cmake enchant
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="$HOME" ..
          make
          make test
          make check
          make install
          make installcheck
workflows:
  version: 2
  workflow:
    jobs:
      - debian
      - macos
