version: 2
jobs:
  arch:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run: pacman --noconfirm --refresh --sync cmake clang enchant make
      - run: ./.ci
  debian:
    docker:
      - image: debian
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y build-essential cmake libenchant-dev man
      - run: .ci
  fedora:
    docker:
      - image: fedora
    steps:
      - checkout
      - run: dnf -y install cmake enchant-devel findutils gcc man
      - run: .ci
  macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: brew install cmake enchant
      - run: .ci
workflows:
  version: 2
  workflow:
    jobs:
      # arch
      - debian
      - fedora
      - macos
